name: httpie-testing
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - ld_impl_linux-64=2.43
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libnsl=2.0.1
  - libsqlite=3.47.0
  - libuuid=2.38.1
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.2
  - pip=24.2
  - python=3.10.0
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.47.0
  - tk=8.6.13
  - tzdata=2024b
  - wheel=0.44.0
  - xz=5.2.6
  - pip:
      - blinker==1.8.2
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - coverage==7.6.4
      - defusedxml==0.7.1
      - exceptiongroup==1.2.2
      - flask==3.0.3
      - httpie==3.2.3
      - idna==3.10
      - iniconfig==2.0.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - mdurl==0.1.2
      - multidict==6.1.0
      - packaging==24.1
      - pluggy==1.5.0
      - pygments==2.18.0
      - pysocks==1.7.1
      - pytest==8.3.3
      - pytest-cov==5.0.0
      - requests==2.31.0
      - requests-toolbelt==1.0.0
      - rich==13.9.3
      - tomli==2.0.2
      - typing-extensions==4.12.2
      - urllib3==2.2.3
      - werkzeug==3.0.6
